# Generated by Django 4.2.7 on 2023-12-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="NftMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="band")),
                ("description", models.CharField(max_length=2000)),
                ("cover_file_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "metadata_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("profile_type", models.CharField(max_length=20)),
                ("price", models.FloatField()),
            ],
        ),
    ]
