# Generated by Django 4.2.7 on 2024-01-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderhistory",
            old_name="price",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="orderhistory",
            old_name="metadata_identifier",
            new_name="organization",
        ),
        migrations.RemoveField(
            model_name="orderhistory",
            name="profile_type",
        ),
    ]
