# Generated by Django 4.2.7 on 2023-12-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="eth_address",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="payment_type",
            field=models.CharField(default="undefined", max_length=20),
        ),
    ]
